import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./theme-provider"; // ← これを追加
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MySite",
  description: "Generated by create next app",
  metadataBase: new URL("https://example.com"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`${inter.className} bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-50`}
      >
        <Providers>
          <header className="border-b bg-white/80 dark:bg-gray-800/80 backdrop-blur sticky top-0 z-10">
            <div className="max-w-5xl mx-auto flex justify-between items-center px-6 py-4">
              <Link
                href="/"
                className="text-xl font-bold text-blue-600 dark:text-blue-400"
              >
                MySite
              </Link>
              <nav className="space-x-4 text-sm">
                <Link href="/about" className="hover:text-blue-500">
                  自己紹介
                </Link>
                <Link href="/blog" className="hover:text-blue-500">
                  ブログ
                </Link>
                <Link href="/tools" className="hover:text-blue-500">
                  ツール
                </Link>
                <Link href="/contact" className="hover:text-blue-500">
                  お問い合わせ
                </Link>
              </nav>
            </div>
          </header>

          <main className="max-w-5xl mx-auto px-6 py-8">{children}</main>

          <footer className="border-t text-center text-sm py-6 text-gray-500 dark:text-gray-400">
            © {new Date().getFullYear()} MySite
          </footer>
        </Providers>
      </body>
    </html>
  );
}
